"""
Turn results/SEA_NET/leaderboard.csv into the appendix longtable
(tables/leaderboard.tex, which sections/A1_appendix.tex \\input's).

Why a script and not typing: 72 rows copied by hand is 72 chances to introduce
a wrong digit. This reads the same CSV every other number in the paper comes
from, so the appendix table cannot drift from the source.

Run from anywhere:
    python ICLR_2025_Report/Paper_ICLR2027/tools/make_leaderboard_tex.py
"""
import csv
import pathlib

HERE = pathlib.Path(__file__).resolve()
PAPER = HERE.parent.parent                 # .../Paper_ICLR2027
ROOT = PAPER.parent.parent                 # .../SEA_NET (project root)
SRC = ROOT / "results" / "SEA_NET" / "leaderboard.csv"
OUT = PAPER / "tables" / "leaderboard.tex"

# UCR numbers we refuse to print: this run finished only 6 of 85 datasets, so
# its mean is not comparable with the other rows (issue I6 in PAPER_ISSUES.md).
DROP_UCR = {"seanet_bottleneck_adaptive"}

# short, readable names for the encoder / pooling columns
ENC = {
    "sea_mstcn_sep": "plain", "sea_mstcn_sep_bottleneck": "bottleneck",
    "sea_mstcn_sep_gated": "gated", "sea_mstcn_sep_inputgate": "input-gated",
    "sea_mstcn_sep_spiketrend": "spike/trend", "sea_mstcn_sep_recon": "recon",
    "sea_multiscale_channels": "ms-channels", "sea_multiscale_pyramid": "ms-pyramid",
    "mil_inceptiontime": "InceptionTime", "mil_resnet": "ResNet", "mil_fcn": "FCN",
}
POOL = {
    "sea_topk_conjunctive": "Top-$k$", "sea_classwise_conjunctive": "class-wise",
    "sea_softmax_conjunctive": "softmax", "sea_adaptive_classwise": "adaptive",
    "sea_attention_max": "attn-max", "sea_gated_attention": "gated-attn",
    "sea_dualstream_conjunctive": "dual-stream",
    "mil_conjunctive": "conjunctive*", "mil_additive": "additive*",
    "mil_attention": "attention*",
}


def tex(s):
    """Escape the few characters that would break LaTeX in a model name."""
    return s.replace("_", r"\_").replace("&", r"\&").replace("%", r"\%")


def num(value, decimals):
    """Format a number, or an em dash when the cell is empty."""
    if value is None or value == "":
        return "---"
    return f"{float(value):.{decimals}f}"


rows = []
with SRC.open(newline="", encoding="utf-8") as fh:
    for r in csv.DictReader(fh):
        ucr = "" if r["config"] in DROP_UCR else r["ucr85_acc"]
        rows.append(" & ".join([
            r["rank"],
            r"\texttt{" + tex(r["config"]) + "}",
            ENC.get(r["encoder"], tex(r["encoder"])),
            POOL.get(r["pooling"], tex(r["pooling"])),
            num(r["web_acc"], 3),
            num(r["web_aopcr"], 2),
            num(r["web_ndcg"], 3),
            num(ucr, 4),
            f"{int(r['params']):,}".replace(",", "{,}"),
        ]) + r" \\")

header = r"""% GENERATED by tools/make_leaderboard_tex.py from
% results/SEA_NET/leaderboard.csv -- do not edit by hand.
{\scriptsize
\setlength{\tabcolsep}{3pt}
\begin{longtable}{rlllcccrr}
\caption{All 72 encoder--head combinations, ordered by \webtraffic{} accuracy. A dash in the
\ucr{} column means the combination was tested on \webtraffic{} only. Pooling heads marked
$^{*}$ are \millet{}'s own, used unchanged.}
\label{tab:app_leaderboard} \\
\toprule
\# & \textbf{Configuration} & \textbf{Encoder} & \textbf{Head} &
Acc. & AOPCR & \ndcg{} & \ucr{}-85 & Params \\
\midrule
\endfirsthead
\multicolumn{9}{l}{\emph{\Cref{tab:app_leaderboard} continued from the previous page.}} \\
\toprule
\# & \textbf{Configuration} & \textbf{Encoder} & \textbf{Head} &
Acc. & AOPCR & \ndcg{} & \ucr{}-85 & Params \\
\midrule
\endhead
\midrule
\multicolumn{9}{r}{\emph{continued on the next page}} \\
\endfoot
\bottomrule
\endlastfoot
"""

footer = "\\end{longtable}}\n"

OUT.parent.mkdir(parents=True, exist_ok=True)
OUT.write_text(header + "\n".join(rows) + "\n" + footer, encoding="utf-8")
print(f"wrote {OUT} with {len(rows)} rows")
