"""
scripts/make_cross_configs.py - write the FULL cross product of our encoders x our poolings as sv4 configs.

Why: we want to find the best encoder + pooling COMBINATION, so we make one config file per pair. We only
cross OUR OWN parts (the paper baselines - inceptiontime/fcn/resnet encoders and the millet
additive/conjunctive poolings - are kept out on purpose; they run separately as baselines).

Safe to run again: if a combo already has a config file it is SKIPPED (never overwritten), so the ones we
already made (all the "classwise" ones, plus gated_last x topk / attnmax) are left untouched. That plus
`re_train: false` in configs/main.yaml means finished work is never redone.

Everything uses the SAME small recipe (d=64, 4 blocks, the shared training block below), so the only thing
that changes between files is the encoder and the pooling - a fair comparison. Run it with:

    python scripts/make_cross_configs.py
"""
import os

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))   # project root
SV4 = os.path.join(HERE, "configs", "models", "sv4")

# ---- our encoders: short name -> the YAML lines for its "encoder" block ----
# all share d=64 / 4 blocks; only the type (and a couple of extra knobs) differ.
ENC_COMMON = "  d: 64\n  n_blocks: 4\n  dropout: 0.2\n  max_dilation: 16\n  kernels: [5, 11, 23]\n"
ENCODERS = {
    "slim":       "  type: mstcn_sep\n" + ENC_COMMON,                                   # plain encoder
    "gated_max":  "  type: mstcn_sep_gated\n" + ENC_COMMON + "  summary: max\n",
    "gated_mean": "  type: mstcn_sep_gated\n" + ENC_COMMON + "  summary: mean\n",
    "gated_last": "  type: mstcn_sep_gated\n" + ENC_COMMON + "  summary: last\n",
    "spiketrend": "  type: mstcn_sep_spiketrend\n" + ENC_COMMON + "  summary: last\n  d_spike: 16\n  smooth_kernel: 5\n",
    "bottleneck": "  type: mstcn_sep_bottleneck\n" + ENC_COMMON + "  bottleneck_ratio: 4\n",
    "inputgate":  "  type: mstcn_sep_inputgate\n" + ENC_COMMON + "  gate_kernel: 7\n",
    "recon":      "  type: mstcn_sep_recon\n" + ENC_COMMON + "  d_res: 16\n",
}

# ---- our poolings: short name -> the YAML lines for its "pooling" block ----
POOL_COMMON = "  d_attn: 8\n  dropout: 0.2\n  positional_encoding: true\n"
POOLINGS = {
    "classwise": "  type: classwise_conjunctive\n" + POOL_COMMON,
    "softmax":   "  type: softmax_conjunctive\n" + POOL_COMMON + "  temperature: 1.0\n",
    "adaptive":  "  type: adaptive_classwise\n" + POOL_COMMON + "  init_beta: 0.3\n",
    "topk":      "  type: topk_conjunctive\n" + POOL_COMMON + "  top_frac: 0.1\n",
    "attnmax":   "  type: attention_max\n" + POOL_COMMON + "  init_lam: 0.5\n",
}

# the training recipe is identical for every combo (so the only difference is encoder + pooling)
TRAINING = (
    "training:\n"
    "  n_epochs: 400\n"
    "  patience: 60\n"
    "  max_batch: 16\n"
    "  learning_rate: 0.00125\n"
    "  weight_decay: 0.00012\n"
    "  label_smoothing: 0.13\n"
    "  lambda_entropy: 0.01\n"
    "  min_train_for_val: 100\n"
    "  val_frac: 0.2\n"
    "  optimizer: adam\n"
)

# Combos that already have a config under a DIFFERENT file name (so we must not make a second one for the
# same pair). The "classwise" column is all 8 encoders (files seanet_<enc>.yaml); plus these two:
ALREADY = {("gated_last", "topk"), ("gated_last", "attnmax")}


def config_text(enc_name: str, pool_name: str) -> str:
    """Build the full YAML text for one encoder+pooling combo."""
    model_name = f"seanet_{enc_name}_{pool_name}"
    return (
        f"# sv4/{model_name}.yaml - AUTO-GENERATED by scripts/make_cross_configs.py\n"
        f"# encoder '{enc_name}' + pooling '{pool_name}'. Same small recipe as every other sv4 combo,\n"
        f"# so any difference in the results comes only from this encoder+pooling pair.\n"
        f"#\n"
        f"# Run it (WebTraffic by default):  python main.py run --model sv4/{model_name}\n\n"
        f"name: {model_name}\n"
        f"use_params: default\n\n"
        f"encoder:\n{ENCODERS[enc_name]}\n"
        f"pooling:\n{POOLINGS[pool_name]}\n"
        f"{TRAINING}"
    )


def main() -> None:
    os.makedirs(SV4, exist_ok=True)
    made, skipped = 0, 0
    # we only need the NON-classwise poolings here (the classwise column already exists as seanet_<enc>.yaml)
    for enc_name in ENCODERS:
        for pool_name in ("softmax", "adaptive", "topk", "attnmax"):
            if (enc_name, pool_name) in ALREADY:
                skipped += 1
                continue
            path = os.path.join(SV4, f"seanet_{enc_name}_{pool_name}.yaml")
            if os.path.exists(path):                      # never overwrite an existing config
                skipped += 1
                continue
            with open(path, "w") as f:
                f.write(config_text(enc_name, pool_name))
            made += 1
            print(f"  wrote sv4/seanet_{enc_name}_{pool_name}.yaml")
    print(f"\ndone: {made} new config(s) written, {skipped} skipped (already there).")


if __name__ == "__main__":
    main()
